### ISSUE TITLE
Bug with exiting a paused visualistion

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_visualiser#21]
In visualisation mode, if you pause a simulation and then close the visualisation window the simulation remains paused with no way to resume. 

Either:

+ Unpause the sim on exit of visualisastion, and allow the sim to continue
+ Stop the simulation when the visualisation window is closed (i.e. FLAME GPU 1 behaviour)

**Comment by Robadob** [comment]
Might be as simple as adding

```c
if (pause_guard)
    delete pause_guard;
```

to `Visualiser::close()`

**Comment by ptheywood** [comment]
Unfortunately this doesn't seem to be the case. I'm looking into it.

**Comment by Robadob** [comment]
Drop it at the end of `run()` instead then?
