### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2_visualiser#23]
Being able to resize the visualisation window would be nice.

**Comment by Robadob** [comment]
For some reason that line of code is/was commented out in sdl_exp, so i left it commented out. Didn't do a git blame to see why.

**Comment by Robadob** [comment]
https://wiki.libsdl.org/SDL_SetWindowResizable

Just needs that calling on window creation and the below uncommenting

```
		//case SDL_WINDOWEVENT:
		//	if (e.window.event == SDL_WINDOWEVENT_RESIZED || e.window.event == SDL_WINDOWEVENT_SIZE_CHANGED)
		//		resizeWindow();
		//	break;
```
May need to remove the call to `resizeWindow()` on fullscreen, assuming that triggers the window event.

**Comment by Robadob** [comment]
Appears that was commentd out when i merged something from OpenVR branch, so probably is safe.
